services:
  postgres:
    container_name: payment_postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    container_name: payment_rabbitmq
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBIT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASS}"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"'
    ports:
      - "127.0.0.1:15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    container_name: payment_api
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    container_name: payment_migrations
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    restart: "no"

  outbox_publisher:
    container_name: payment_outbox_publisher
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: python -m entrypoints.outbox_publisher
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  consumer:
    container_name: payment_consumer
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: python -m entrypoints.consumer
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

volumes:
  postgres_data:
  rabbitmq_data:
